# Régressions linéaires : régression linéaire simple

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [5]:
data = pd.read_csv('~/Documents/Ia-Datasets/regressions/headbrain.csv', index_col=0)

data.head()

Age Range  Head Size(cm^3)  Brain Weight(grams)
Gender                                                 
1               1             4512                 1530
1               1             3738                 1297
1               1             4261                 1335
1               1             3777                 1282
1               1             4177                 1590

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237 entries, 1 to 2
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age Range            237 non-null    int64
 1   Head Size(cm^3)      237 non-null    int64
 2   Brain Weight(grams)  237 non-null    int64
dtypes: int64(3)
memory usage: 7.4 KB


Question : Est-ce que le poid du cerveau influe sur la taille de la tête ?

Note sur le grahique, on voit 2 espaces où il n'y a pas de points. C'est parce que les données sont discrètes et non continues.

### Premier modèle avec searborn


In [7]:
from sklearn.linear_model import LinearRegression

In [15]:
X = data['Head Size(cm^3)'].values.reshape(-1,1)
Y = data['Brain Weight(grams)'].values.reshape(-1,1)
reg = LinearRegression()
mdl = reg.fit(X, Y)

mdl.coef_


array([[0.26342934]])

In [16]:
mdl.intercept_

array([325.57342105])

In [ ]:
mdl.score(X, Y) # Retourne le r^2

# 64% de la variabilité du poid s'expliquer par la variable de volume (taille de la tête)

In [18]:
mdl.predict([[4000]])

array([[1379.29077901]])

# 3e : Statsmodels ols

In [4]:
import statsmodels.api as sm
import pandas as pd
import numpy as np

## Régréssion polynomiale
- Une seule variable
- Variation de la puissance

In [6]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [8]:
boston = pd.DataFrame(data, columns=["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM",])

boston

ValueError: Shape of passed values is (506, 13), indices imply (506, 6)